#pragma once

typedef unsigned int uint;
typedef unsigned __int8 uint_8;

#define PI 3.14159265358979f
#define PI_HALF PI / 2.0f

#define ENGINE_ENABLED 1
#define ENGINE_DISABLED 0

#define ENGINE_DEBUG				(_DEBUG)
#define ENGINE_DEBUG_MESH			(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_BUFFER			(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_DATATEST		(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_DEBUGCAM		(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_GPUEVENT		(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_GPUPROF		(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_GPUPROF_LOG	(0 && ENGINE_DEBUG_GPUPROF && ENGINE_ENABLED)
#define ENGINE_DEBUG_CPUEVENT		(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_CPUPROF		(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_CPUPROF_LOG	(0 && ENGINE_DEBUG_CPUPROF && ENGINE_ENABLED)
#define ENGINE_DEBUG_EVENT			(ENGINE_DEBUG_GPUEVENT || ENGINE_DEBUG_CPUEVENT)
#define ENGINE_DEBUG_RESOURCEVIEW	(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_EVENTRESOURCE	(ENGINE_DEBUG_GPUEVENT && ENGINE_DEBUG_RESOURCEVIEW && ENGINE_ENABLED)
#define ENGINE_DEBUG_RESOURCENAME	(0 && ENGINE_DEBUG_RESOURCEVIEW && ENGINE_ENABLED)
#define ENGINE_DEBUG_MEMVIEW		(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_STATS			(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_READBACK		(ENGINE_DEBUG_MEMVIEW || ENGINE_DEBUG_STATS)
//will only enable during the extra debug TODO : add debug level so I can easily toggle things on/off
#define ENGINE_DEBUG_CLEARGBUFFER	0 //(ENGINE_DEBUG && ENGINE_ENABLED)