#pragma once

typedef unsigned int uint;
typedef unsigned __int8 uint_8;

#define PI 3.14159265358979f
#define PI_HALF PI / 2.0f

#define ENGINE_ENABLED 1
#define ENGINE_DISABLED 0

#define ENGINE_DEBUG				(_DEBUG)
#define ENGINE_DEBUG_MESH			(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_BUFFER			(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_DATATEST		(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_DEBUGCAM		(ENGINE_DEBUG && ENGINE_ENABLED)
#define ENGINE_DEBUG_CLEARGBUFFER	(ENGINE_DEBUG && ENGINE_ENABLED)